/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-09 10:29:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mycom.d3.vo.MemberVO;

public final class topPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
  MemberVO userInfo = (MemberVO) session.getAttribute("userInfo");	

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Droid+Serif:700,400,400italic,700italic'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/*********************************************************************************/\r\n");
      out.write("/* top                                                                          */\r\n");
      out.write("/*********************************************************************************/\r\n");
      out.write("\r\n");
      out.write("/*상단로고 buy yourself,login,join*/\r\n");
      out.write("#logo-wrapper {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tbackground-color: #282828;\r\n");
      out.write("\tpadding: 1px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo h1 a {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 40px;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-family: 'Droid Serif', serif;\r\n");
      out.write("\tfont-size: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo a {\r\n");
      out.write("\t/* display: block; */\r\n");
      out.write("\t/* text-transform: uppercase;  */\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo span {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tright: 50px;\r\n");
      out.write("\tletter-spacing: 0px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\t/* color: rgba(255, 255, 255, .7); */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*********************************************************************************/\r\n");
      out.write("/* nav                                                                          */\r\n");
      out.write("/*********************************************************************************/\r\n");
      out.write("#top_nav {\r\n");
      out.write("\tpadding: 1px 0px 1px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top_nav>ul>li {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top_nav>ul>li:last-child {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top_nav>ul>li>a, #nav>ul>li>span {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 12px 24px;\r\n");
      out.write("\tletter-spacing: 0px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tcolor: #db3b5d;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top_nav li.active a {\r\n");
      out.write("\tbackground: #1F577C;\r\n");
      out.write("\tborder-radius: 30px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top_nav>ul>li>ul {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function(){  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t    $(\"ul.subnav\").parent().append(\"<span></span>\"); //제이쿼리 시동하고 ul.subnav뒤에 비어있는 span태그를 추가  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t    $(\"ul.topnav li span\").hover(function() { //클릭시 다음 이벤트를 subnav에 적용 \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t        $(this).parent().find(\"ul.subnav\").slideDown('fast').show(); //클릭시 subnav을 아래로 내림\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t        $(this).parent(\"li\").hover(function(){  \r\n");
      out.write("\t\t              $(this).parent().find(\"ul.subnav\").slideUp('slow'); //마우스 벗어났을때 원위치시킴  \r\n");
      out.write("\t\t          });  \t\t  \r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        }).hover(function() {  \r\n");
      out.write("\t\t            $(this).addClass(\"subhover\"); //마우스 오버시 subhover 클래스 추가  \r\n");
      out.write("\t\t        }, function(){  //On Hover Out  \r\n");
      out.write("\t\t            $(this).removeClass(\"subhover\"); //마우스 아웃시 subhover클래스 제거  \r\n");
      out.write("\t\t    });  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t});  \r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"logo-wrapper\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- Logo -->\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t<h2>\r\n");
      out.write("\t\t\t\t<a href=\"main.do\">zzzzzzzz</a>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t");
/*if(userInfo != null) {
      out.write("\r\n");
      out.write("\t\t<!-- \t<h2>");
      out.print(userInfo.getId());
      out.write("\r\n");
      out.write("\t\t\t\tconnected\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<span><a href=\"logout.do\">LogOut</a>&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
}else { 
      out.write("\r\n");
      out.write("\t\t\t<span><a href=\"login.do\">Login</a>&nbsp;&nbsp;&nbsp; <a\r\n");
      out.write("\t\t\t\thref=\"join.do\">Join</a></span>\r\n");
      out.write("\t\t\t");
} */
      out.write("\r\n");
      out.write(" -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<nav id=\"top_nav\">\r\n");
      out.write("\t\t<ul class=\"topnav\">\r\n");
      out.write("\t\t\t<li><a href=\"main.do\">장애 사항 조회</a>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"blist.do\">전체조회</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"foodlist.do\">xxx</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href=\"slist.do\">장애 조치 조회</a>\r\n");
      out.write("\t\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"slist.do\">전체조회</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"foodlist.do\">xxx</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
