/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-09 10:31:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("userInfo"), request);
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원가입</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link\n");
      out.write("\thref=\"http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("a,a:hover,a:visited {\n");
      out.write("\tcolor: #fff;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#controls {\n");
      out.write("\twidth: 250px;\n");
      out.write("\theight: 400px;\n");
      out.write("\tbackground: gray;\n");
      out.write("\tcolor: black;\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 300px;\n");
      out.write("\tleft: 500px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tborder: 2px solid #000;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#pop_bt {\n");
      out.write("\tborder: 1px solid #000;\n");
      out.write("\twidth: 100px;\n");
      out.write("\tright: 50px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tpadding: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#close {\n");
      out.write("\twidth: 100px;\n");
      out.write("\tmargin: auto;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.10.2.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.9.1.min.js\"></script>\n");
      out.write("   <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("var flag = 1;\n");
      out.write("var flag2 = 1;\n");
      out.write("   $(document).ready(function() {\n");
      out.write("\t   $(\"#idchecked\").on(\"click\" , function() {\n");
      out.write("\t\t   var id = $(\"#id\").val();\n");
      out.write("\t\t\tif (id.length < 1 || id == null) {\n");
      out.write("\t\t\t\talert(\"중복체크할 이메일을 입력하십시오\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse{\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\turl:'http://localhost:8088/d3/idcheck.do',\n");
      out.write("\t\t\t\t\ttype : \"post\", \n");
      out.write("\t\t\t\t\tdata:{id:id},\n");
      out.write("\t\t\t\t\tdataType : \"json\",\n");
      out.write("\t\t\t\t\tsuccess:function(data){ \n");
      out.write("\t\t\t\t\t\tif(data.id==\"1\"){\n");
      out.write("\t\t\t\t\t\t\tflag=0;\n");
      out.write("\t\t\t\t\t\t\t$('.idcheckran').empty();\n");
      out.write("\t\t\t\t\t\t\t$('.idcheckran').append('사용가능한 이메일입니다.');\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\telse{\n");
      out.write("\t\t\t\t\t\t\tflag=1;\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$('.idcheckran').empty();\n");
      out.write("\t\t\t\t\t\t\t$('.idcheckran').append('이미 사용중인 이메일입니다.');\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t           \n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t}\n");
      out.write("\t\t   \n");
      out.write("\t   });\n");
      out.write("\t\n");
      out.write("    $('#pop_bt').click(function() {\n");
      out.write("     $('#controls').show();\n");
      out.write("    });\n");
      out.write("    $('#input').click(function() {   \t\n");
      out.write("    });\n");
      out.write("   });\n");
      out.write("\n");
      out.write("   var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("   $(function() {\n");
      out.write("\n");
      out.write("\t      $(\"form\").submit(function() {\n");
      out.write("\t          if (flag ==1) {\n");
      out.write("\t        \t  alert(\"이메일 중복을 검사하세요.\");\n");
      out.write("\t\t          $(\"#id\").focus();\n");
      out.write("\t\t          return false;\n");
      out.write("\t          }\n");
      out.write("\t          \n");
      out.write("\n");
      out.write("\t       });\n");
      out.write("\t     \t   \n");
      out.write("\n");
      out.write("      $(\"form\").submit(function() {\n");
      out.write("         if ($(\"#password\").val().length >= 8) {\n");
      out.write("            return true;\n");
      out.write("         }\n");
      out.write("         alert(\"비밀번호를 8자 이상 입력하세요.\");\n");
      out.write("         $(\"#password\").focus();\n");
      out.write("         return false;\n");
      out.write("\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"form\").submit(function() {\n");
      out.write("         var lcase = new RegExp(\"[a-z]+\");\n");
      out.write("         if (lcase.test($(\"#password\").val())) {\n");
      out.write("            return true;\n");
      out.write("         }\n");
      out.write("         alert(\"영어 소문자 1자 이상 사용하세요.\");\n");
      out.write("         $(\"#password\").focus();\n");
      out.write("         return false;\n");
      out.write("\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"form\").submit(function() {\n");
      out.write("         var num = new RegExp(\"[0-9]+\");\n");
      out.write("         if (num.test($(\"#password\").val())) {\n");
      out.write("            return true;\n");
      out.write("         }\n");
      out.write("         alert(\"숫자 1자 이상 사용하세요.\");\n");
      out.write("         $(\"#password\").focus();\n");
      out.write("         return false;\n");
      out.write("\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"form\").submit(function() {\n");
      out.write("         var password = $(\"#password\").val().trim();\n");
      out.write("         var password_confirm = $(\"#password_confirm\").val().trim();\n");
      out.write("         if (password != password_confirm) {\n");
      out.write("            alert(\"비밀번호가 다릅니다.\");\n");
      out.write("            return false;\n");
      out.write("         }\n");
      out.write("\n");
      out.write("         return true;\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"input[type=password]\").keyup(function() {\n");
      out.write("\n");
      out.write("         var lcase = new RegExp(\"[a-z]+\");\n");
      out.write("         var num = new RegExp(\"[0-9]+\");\n");
      out.write("\n");
      out.write("         if ($(\"#password\").val().length >= 8) {\n");
      out.write("            $(\"#8char\").removeClass(\"glyphicon-remove\");\n");
      out.write("            $(\"#8char\").addClass(\"glyphicon-ok\");\n");
      out.write("            $(\"#8char\").css(\"color\", \"#00A41E\");\n");
      out.write("         } else {\n");
      out.write("            $(\"#8char\").removeClass(\"glyphicon-ok\");\n");
      out.write("            $(\"#8char\").addClass(\"glyphicon-remove\");\n");
      out.write("            $(\"#8char\").css(\"color\", \"#FF0004\");\n");
      out.write("         }\n");
      out.write("\n");
      out.write("         if (lcase.test($(\"#password\").val())) {\n");
      out.write("            $(\"#lcase\").removeClass(\"glyphicon-remove\");\n");
      out.write("            $(\"#lcase\").addClass(\"glyphicon-ok\");\n");
      out.write("            $(\"#lcase\").css(\"color\", \"#00A41E\");\n");
      out.write("         } else {\n");
      out.write("            $(\"#lcase\").removeClass(\"glyphicon-ok\");\n");
      out.write("            $(\"#lcase\").addClass(\"glyphicon-remove\");\n");
      out.write("            $(\"#lcase\").css(\"color\", \"#FF0004\");\n");
      out.write("         }\n");
      out.write("\n");
      out.write("         if (num.test($(\"#password\").val())) {\n");
      out.write("            $(\"#num\").removeClass(\"glyphicon-remove\");\n");
      out.write("            $(\"#num\").addClass(\"glyphicon-ok\");\n");
      out.write("            $(\"#num\").css(\"color\", \"#00A41E\");\n");
      out.write("         } else {\n");
      out.write("            $(\"#num\").removeClass(\"glyphicon-ok\");\n");
      out.write("            $(\"#num\").addClass(\"glyphicon-remove\");\n");
      out.write("            $(\"#num\").css(\"color\", \"#FF0004\");\n");
      out.write("         }\n");
      out.write("\n");
      out.write("         if ($(\"#password\").val() == $(\"#password_confirm\").val()) {\n");
      out.write("            $(\"#pwmatch\").removeClass(\"glyphicon-remove\");\n");
      out.write("            $(\"#pwmatch\").addClass(\"glyphicon-ok\");\n");
      out.write("            $(\"#pwmatch\").css(\"color\", \"#00A41E\");\n");
      out.write("         } else {\n");
      out.write("            $(\"#pwmatch\").removeClass(\"glyphicon-ok\");\n");
      out.write("            $(\"#pwmatch\").addClass(\"glyphicon-remove\");\n");
      out.write("            $(\"#pwmatch\").css(\"color\", \"#FF0004\");\n");
      out.write("         }\n");
      out.write("      });\n");
      out.write("\n");
      out.write("   });\n");
      out.write("   \n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<form class=\"form-horizontal\" action='joinImpl.do' method=\"POST\">\n");
      out.write("\t\t<fieldset>\n");
      out.write("\t\t\t<div id=\"legend\">\n");
      out.write("\t\t\t\t사용자 등록\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"control-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t\t<!-- E-mail -->\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"id\">이메일</label>\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"id\" name=\"id\" placeholder=\"\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"input-xlarge\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> \n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"중복확인\" name=\"idchecked\" id=\"idchecked\" >\n");
      out.write("\t\t\t\t\t\t\t<input\n");
      out.write("\t\t\t\t\t\t\ttype=\"hidden\" name=\"isDupId\" id=\"isDupId\" />\n");
      out.write("\t\t\t\t\t\t<p class=\"help-block\">이메일을 입력해 주세요.</p><p class=\"idcheckran\"></p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t\t<!-- Password-->\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"password\">비밀번호</label>\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"password\" name=\"password\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"\" class=\"input-xlarge\">\n");
      out.write("\t\t\t\t\t\t<p class=\"help-block\">비밀번호를 입력해 주세요.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<span id=\"8char\" class=\"glyphicon glyphicon-remove\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #FF0004;\"></span> 8 Characters Long<br> <span\n");
      out.write("\t\t\t\t\t\t\tid=\"lcase\" class=\"glyphicon glyphicon-remove\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #FF0004;\"></span> One Lowercase Letter<br> <span\n");
      out.write("\t\t\t\t\t\t\tid=\"num\" class=\"glyphicon glyphicon-remove\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #FF0004;\"></span> One Number\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t\t<!-- Password -->\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"password_confirm\">비밀번호 확인</label>\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"password_confirm\"\n");
      out.write("\t\t\t\t\t\t\tname=\"password_confirm\" placeholder=\"\" class=\"input-xlarge\">\n");
      out.write("\t\t\t\t\t\t<p class=\"help-block\">비밀번호를 재입력해 주세요.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<span id=\"pwmatch\" class=\"glyphicon glyphicon-remove\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #FF0004;\"></span> Passwords Match\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Username -->\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"M_name\">닉네임</label>\n");
      out.write("\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"M_name\" name=\"M_name\" placeholder=\"\"\n");
      out.write("\t\t\t\t\t\tclass=\"input-xlarge\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.M_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("\t\t\t\t\t<p class=\"help-block\">닉네임을 입력해 주세요.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t<!-- Button -->\n");
      out.write("\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-success\">등록</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</fieldset>\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
